languageCode: zh-Hans
languageName: ä¸­æ–‡
languageDirection: ltr
weight: 1
params:
  dateFormat: 2006å¹´January2æ—¥
  author:
    name: Holger Huo
    image: images/author-image.png
    headline: ä½ å¥½ ğŸ‘‹ æˆ‘æ˜¯ä¸€åå°åœ°è¯­æœ¬ç§‘ç”Ÿï¼ŒåŒæ—¶ä¹Ÿæ˜¯ç§‘æŠ€ä¸å¼€æºçš„çˆ±å¥½è€…ã€‚æˆ‘ä¼šåœ¨åšå®¢ä¸­è®°å½•æœ‰å…³æŠ€æœ¯ã€è¯­è¨€ä¸æˆ‘çš„ç”Ÿæ´»ç›¸å…³çš„å†…å®¹ã€‚æ¬¢è¿ä½ çš„å…³æ³¨ï¼
    links:
      - email: mailto:i@holger.one
      - facebook: https://www.facebook.com/HolgerHuo/
      - github: https://github.com/HolgerHuo
      - instagram: https://www.instagram.com/holgerhuo/
      - lastfm: https://last.fm/user/holger_huo
      - mastodon: https://mast.dragon-fly.club/@holgerhuo
      - x-twitter: https://twitter.com/@holger_huo
  mainSections:
    - posts
    - pages
  description: ç¼–ç¨‹æ—¥å¿—ä¸ç”Ÿæ´»æ„Ÿæƒ³ã€‚æ¥è‡ªä¸€ä½å°åœ°è¯­æœ¬ç§‘ç”Ÿä¸ä¸šä½™å¼€å‘è€…ã€‚
  article:
    sharingLinks:
      - weibo
      - douban
      - qq
      - mastodon
      - twitter
      - email
      - facebook
      - telegram
  keywords:
    - å¼€æº
    - ç¼–ç¨‹
    - ç”Ÿæ´»
    - å¼€å‘
    - ç§‘æŠ€
    - åšå®¢
    - Linux